---


    - name: Install HTTPD
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "Amazon" or ansible_distribution == "Fedora"

    - name: Start HTTPD
      service:
        name: httpd
        state: started
      when: ansible_distribution == "Amazon" "Amazon" or ansible_distribution == "Fedora"

    - name: Enable HTTPD
      service:
        name: httpd
        enabled: yes
      when: ansible_distribution == "Amazon" "Amazon" or ansible_distribution == "Fedora"

    - name: Install Apache2 on Ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - name: Start Apache2 on Ubuntu
      service:
        name: apache2
        state: started
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - name: Enable Apache2 on Ubuntu
      service:
        name: apache2
        enabled: yes
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"


...